name: Deploy to Booker POS to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write production env config
        run: |
         return [
              'DB_HOST' => '${{ secrets.MYSQL_HOSTNAME }}',
              'DB_USER' => '${{ secrets.MYSQL_USERNAME }}',
              'DB_PASS' => '${{ secrets.MYSQL_PASSWORD }}',
              'DB_NAME' => '${{ secrets.MYSQL_DATABASE_NAME }}',
              'ENVIRONMENT' => 'production',
          ];
          EOF

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: ./htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/logs/**